server:
  port: 8087

spring:
  application:
    name: brf-mwe-server
  main:
    banner-mode: off
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: 'password'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console:
      enabled: true
